name: tensorplay-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - pip
  - pytest
  - black
  - isort
  - flake8
  - mypy
  - matplotlib
  - pip:
    - -e .  # 以可编辑模式安装当前项目