# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bluemoon/projects/TensorPlay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bluemoon/projects/TensorPlay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bluemoon/projects/TensorPlay/CMakeFiles /home/bluemoon/projects/TensorPlay//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bluemoon/projects/TensorPlay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_code

# Build rule for target.
generate_code: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_code
.PHONY : generate_code

# fast build rule for target.
generate_code/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_code.dir/build.make CMakeFiles/generate_code.dir/build
.PHONY : generate_code/fast

#=============================================================================
# Target rules for targets named _C

# Build rule for target.
_C: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _C
.PHONY : _C

# fast build rule for target.
_C/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_C.dir/build.make CMakeFiles/_C.dir/build
.PHONY : _C/fast

#=============================================================================
# Target rules for targets named build_python

# Build rule for target.
build_python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_python
.PHONY : build_python

# fast build rule for target.
build_python/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_python.dir/build.make CMakeFiles/build_python.dir/build
.PHONY : build_python/fast

#=============================================================================
# Target rules for targets named dnnl

# Build rule for target.
dnnl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dnnl
.PHONY : dnnl

# fast build rule for target.
dnnl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/onednn-build/src/CMakeFiles/dnnl.dir/build.make _deps/onednn-build/src/CMakeFiles/dnnl.dir/build
.PHONY : dnnl/fast

#=============================================================================
# Target rules for targets named dnnl_common

# Build rule for target.
dnnl_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dnnl_common
.PHONY : dnnl_common

# fast build rule for target.
dnnl_common/fast:
	$(MAKE) $(MAKESILENT) -f _deps/onednn-build/src/common/CMakeFiles/dnnl_common.dir/build.make _deps/onednn-build/src/common/CMakeFiles/dnnl_common.dir/build
.PHONY : dnnl_common/fast

#=============================================================================
# Target rules for targets named dnnl_cpu

# Build rule for target.
dnnl_cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dnnl_cpu
.PHONY : dnnl_cpu

# fast build rule for target.
dnnl_cpu/fast:
	$(MAKE) $(MAKESILENT) -f _deps/onednn-build/src/cpu/CMakeFiles/dnnl_cpu.dir/build.make _deps/onednn-build/src/cpu/CMakeFiles/dnnl_cpu.dir/build
.PHONY : dnnl_cpu/fast

#=============================================================================
# Target rules for targets named dnnl_cpu_x64

# Build rule for target.
dnnl_cpu_x64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dnnl_cpu_x64
.PHONY : dnnl_cpu_x64

# fast build rule for target.
dnnl_cpu_x64/fast:
	$(MAKE) $(MAKESILENT) -f _deps/onednn-build/src/cpu/x64/CMakeFiles/dnnl_cpu_x64.dir/build.make _deps/onednn-build/src/cpu/x64/CMakeFiles/dnnl_cpu_x64.dir/build
.PHONY : dnnl_cpu_x64/fast

#=============================================================================
# Target rules for targets named p10_kernel_default_ReductionKernelsImpl

# Build rule for target.
p10_kernel_default_ReductionKernelsImpl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p10_kernel_default_ReductionKernelsImpl
.PHONY : p10_kernel_default_ReductionKernelsImpl

# fast build rule for target.
p10_kernel_default_ReductionKernelsImpl/fast:
	$(MAKE) $(MAKESILENT) -f p10/CMakeFiles/p10_kernel_default_ReductionKernelsImpl.dir/build.make p10/CMakeFiles/p10_kernel_default_ReductionKernelsImpl.dir/build
.PHONY : p10_kernel_default_ReductionKernelsImpl/fast

#=============================================================================
# Target rules for targets named p10_kernel_avx2_ReductionKernelsImpl

# Build rule for target.
p10_kernel_avx2_ReductionKernelsImpl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p10_kernel_avx2_ReductionKernelsImpl
.PHONY : p10_kernel_avx2_ReductionKernelsImpl

# fast build rule for target.
p10_kernel_avx2_ReductionKernelsImpl/fast:
	$(MAKE) $(MAKESILENT) -f p10/CMakeFiles/p10_kernel_avx2_ReductionKernelsImpl.dir/build.make p10/CMakeFiles/p10_kernel_avx2_ReductionKernelsImpl.dir/build
.PHONY : p10_kernel_avx2_ReductionKernelsImpl/fast

#=============================================================================
# Target rules for targets named p10_kernel_default_StaxPointwiseKernels

# Build rule for target.
p10_kernel_default_StaxPointwiseKernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p10_kernel_default_StaxPointwiseKernels
.PHONY : p10_kernel_default_StaxPointwiseKernels

# fast build rule for target.
p10_kernel_default_StaxPointwiseKernels/fast:
	$(MAKE) $(MAKESILENT) -f p10/CMakeFiles/p10_kernel_default_StaxPointwiseKernels.dir/build.make p10/CMakeFiles/p10_kernel_default_StaxPointwiseKernels.dir/build
.PHONY : p10_kernel_default_StaxPointwiseKernels/fast

#=============================================================================
# Target rules for targets named p10_kernel_avx2_StaxPointwiseKernels

# Build rule for target.
p10_kernel_avx2_StaxPointwiseKernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p10_kernel_avx2_StaxPointwiseKernels
.PHONY : p10_kernel_avx2_StaxPointwiseKernels

# fast build rule for target.
p10_kernel_avx2_StaxPointwiseKernels/fast:
	$(MAKE) $(MAKESILENT) -f p10/CMakeFiles/p10_kernel_avx2_StaxPointwiseKernels.dir/build.make p10/CMakeFiles/p10_kernel_avx2_StaxPointwiseKernels.dir/build
.PHONY : p10_kernel_avx2_StaxPointwiseKernels/fast

#=============================================================================
# Target rules for targets named p10

# Build rule for target.
p10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p10
.PHONY : p10

# fast build rule for target.
p10/fast:
	$(MAKE) $(MAKESILENT) -f p10/CMakeFiles/p10.dir/build.make p10/CMakeFiles/p10.dir/build
.PHONY : p10/fast

#=============================================================================
# Target rules for targets named tpx

# Build rule for target.
tpx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tpx
.PHONY : tpx

# fast build rule for target.
tpx/fast:
	$(MAKE) $(MAKESILENT) -f tpx/CMakeFiles/tpx.dir/build.make tpx/CMakeFiles/tpx.dir/build
.PHONY : tpx/fast

#=============================================================================
# Target rules for targets named stax

# Build rule for target.
stax: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stax
.PHONY : stax

# fast build rule for target.
stax/fast:
	$(MAKE) $(MAKESILENT) -f stax/CMakeFiles/stax.dir/build.make stax/CMakeFiles/stax.dir/build
.PHONY : stax/fast

Unity/unity_0_cxx.o: Unity/unity_0_cxx.cxx.o
.PHONY : Unity/unity_0_cxx.o

# target to build an object file
Unity/unity_0_cxx.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_C.dir/build.make CMakeFiles/_C.dir/Unity/unity_0_cxx.cxx.o
.PHONY : Unity/unity_0_cxx.cxx.o

Unity/unity_0_cxx.i: Unity/unity_0_cxx.cxx.i
.PHONY : Unity/unity_0_cxx.i

# target to preprocess a source file
Unity/unity_0_cxx.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_C.dir/build.make CMakeFiles/_C.dir/Unity/unity_0_cxx.cxx.i
.PHONY : Unity/unity_0_cxx.cxx.i

Unity/unity_0_cxx.s: Unity/unity_0_cxx.cxx.s
.PHONY : Unity/unity_0_cxx.s

# target to generate assembly for a file
Unity/unity_0_cxx.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_C.dir/build.make CMakeFiles/_C.dir/Unity/unity_0_cxx.cxx.s
.PHONY : Unity/unity_0_cxx.cxx.s

Unity/unity_1_cxx.o: Unity/unity_1_cxx.cxx.o
.PHONY : Unity/unity_1_cxx.o

# target to build an object file
Unity/unity_1_cxx.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_C.dir/build.make CMakeFiles/_C.dir/Unity/unity_1_cxx.cxx.o
.PHONY : Unity/unity_1_cxx.cxx.o

Unity/unity_1_cxx.i: Unity/unity_1_cxx.cxx.i
.PHONY : Unity/unity_1_cxx.i

# target to preprocess a source file
Unity/unity_1_cxx.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_C.dir/build.make CMakeFiles/_C.dir/Unity/unity_1_cxx.cxx.i
.PHONY : Unity/unity_1_cxx.cxx.i

Unity/unity_1_cxx.s: Unity/unity_1_cxx.cxx.s
.PHONY : Unity/unity_1_cxx.s

# target to generate assembly for a file
Unity/unity_1_cxx.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_C.dir/build.make CMakeFiles/_C.dir/Unity/unity_1_cxx.cxx.s
.PHONY : Unity/unity_1_cxx.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... build_python"
	@echo "... generate_code"
	@echo "... _C"
	@echo "... dnnl"
	@echo "... dnnl_common"
	@echo "... dnnl_cpu"
	@echo "... dnnl_cpu_x64"
	@echo "... p10"
	@echo "... p10_kernel_avx2_ReductionKernelsImpl"
	@echo "... p10_kernel_avx2_StaxPointwiseKernels"
	@echo "... p10_kernel_default_ReductionKernelsImpl"
	@echo "... p10_kernel_default_StaxPointwiseKernels"
	@echo "... stax"
	@echo "... tpx"
	@echo "... Unity/unity_0_cxx.o"
	@echo "... Unity/unity_0_cxx.i"
	@echo "... Unity/unity_0_cxx.s"
	@echo "... Unity/unity_1_cxx.o"
	@echo "... Unity/unity_1_cxx.i"
	@echo "... Unity/unity_1_cxx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

