# Copyright (c) 2025 zlx. All rights reserved.
# Generated by tools/codegen/gen.py

"""
The tensorplay package offers a simple deep-learning framework
designed for educational purposes and small-scale experiments.
It defines a data structure for multidimensional arrays called Tensor,
on which it encapsulates mathematical operations.
"""

__version__ = "1.0.0rc0"

import os

# Add the directory containing this file to DLL search path on Windows
if os.name == 'nt':
    try:
        lib_path = os.path.join(os.path.dirname(__file__), 'lib')
        if os.path.exists(lib_path):
            os.add_dll_directory(lib_path)
        else:
            os.add_dll_directory(os.path.dirname(__file__))
    except OSError:
        pass

from .tensor import Tensor
from ._C import tensor, from_dlpack, to_dlpack
from .scalar import Scalar
from .device import Device, DeviceType

device = Device

from . import cuda
from . import optim

from .dtype import DType

uint8 = DType.uint8
int8 = DType.int8
int16 = DType.int16
uint16 = DType.uint16
int32 = DType.int32
int64 = DType.int64
float32 = DType.float32
float64 = DType.float64
bool = DType.bool

from ._C import (
    abs, acos, acosh, all, angle, any, arange, argmax, argmin, asin, 
    asinh, atan, atanh, bernoulli, cat, ceil, chunk, clamp, conv2d, cos, 
    cosh, empty, empty_like, eq, exp, eye, floor, full, full_like, ge, 
    gelu, gt, le, lerp, linspace, log, logspace, lt, masked_select, 
    matmul, max, mean, min, mm, ne, neg, norm, normal, ones, ones_like, 
    permute, poisson, pow, prod, rand, rand_like, randint, randint_like, 
    randn, randn_like, randperm, relu, reshape, round, rsqrt, sigmoid, 
    sign, silu, sin, sinh, softmax, split, sqrt, square, squeeze, stack, 
    std, sum, t, tan, tanh, transpose, unbind, unsqueeze, var, zeros, 
    zeros_like, 
)

from ._C import Size

from .functional import *

__all__ = [
    "Tensor", "tensor", "from_dlpack", "Scalar", "Device", "DeviceType", "device",
    "DType", "Size",
    "uint8", "int8", "int16", "uint16", "int32", "int64", "float32", "float64", "bool",
    "abs", "acos", "acosh", "all", "angle", "any", "arange", "argmax", 
    "argmin", "asin", "asinh", "atan", "atanh", "bernoulli", "cat", 
    "ceil", "chunk", "clamp", "conv2d", "cos", "cosh", "empty", 
    "empty_like", "eq", "exp", "eye", "floor", "full", "full_like", "ge", 
    "gelu", "gt", "le", "lerp", "linspace", "log", "logspace", "lt", 
    "masked_select", "matmul", "max", "mean", "min", "mm", "ne", "neg", 
    "norm", "normal", "ones", "ones_like", "permute", "poisson", "pow", 
    "prod", "rand", "rand_like", "randint", "randint_like", "randn", 
    "randn_like", "randperm", "relu", "reshape", "round", "rsqrt", 
    "sigmoid", "sign", "silu", "sin", "sinh", "softmax", "split", "sqrt", 
    "square", "squeeze", "stack", "std", "sum", "t", "tan", "tanh", 
    "transpose", "unbind", "unsqueeze", "var", "zeros", "zeros_like", 
]

from . import __config__