from collections.abc import Iterator, Sequence
import enum
from typing import overload

from numpy.typing import NDArray

from . import (
    autograd as autograd,
    cuda as cuda,
    ops as ops,
    parallel as parallel,
    profiler as profiler
)


class DType(enum.Enum):
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    float32 = 8

    float64 = 9

    int32 = 3

    int64 = 4

    uint32 = 6

    uint64 = 7

    bool = 10

    undefined = 13

float32: DType = DType.float32

float64: DType = DType.float64

int32: DType = DType.int32

int64: DType = DType.int64

uint32: DType = DType.uint32

uint64: DType = DType.uint64

bool: DType = DType.bool

undefined: DType = DType.undefined

class DeviceType(enum.Enum):
    CPU = 0

    CUDA = 1

CPU: DeviceType = DeviceType.CPU

CUDA: DeviceType = DeviceType.CUDA

class Device:
    @overload
    def __init__(self, type: DeviceType, index: int = -1) -> None: ...

    @overload
    def __init__(self, device: str) -> None: ...

    @overload
    def __init__(self, type: str, index: int) -> None: ...

    @property
    def type(self) -> str: ...

    @property
    def index(self) -> int: ...

    def is_cpu(self) -> bool: ...

    def is_cuda(self) -> bool: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __eq__(self, arg: Device, /) -> bool: ...

    def __ne__(self, arg: Device, /) -> bool: ...

class Scalar:
    @overload
    def __init__(self, arg: float, /) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

    @overload
    def __init__(self, arg: bool, /) -> None: ...

    def __repr__(self) -> str: ...

class Size:
    def __init__(self, arg: Sequence[int], /) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> int: ...

    def __iter__(self) -> Iterator[int]: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    @overload
    def __eq__(self, arg: Size, /) -> bool: ...

    @overload
    def __eq__(self, arg: tuple, /) -> bool: ...

    @overload
    def __eq__(self, arg: list, /) -> bool: ...

    def __ne__(self, arg: Size, /) -> bool: ...

class Generator:
    def __init__(self, seed: int = 0) -> None: ...

    def manual_seed(self, seed: int) -> int: ...

    def seed(self) -> int: ...

    def initial_seed(self) -> int: ...

    @property
    def device(self) -> Device: ...

def default_generator() -> Generator: ...

def manual_seed(seed: int) -> None: ...

def seed(seed: int) -> None: ...

def initial_seed() -> int: ...

class TensorBase:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, data: object, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> None: ...

    @property
    def shape(self) -> Size: ...

    @property
    def dtype(self) -> DType: ...

    @property
    def device(self) -> Device: ...

    @property
    def ndim(self) -> int: ...

    def dim(self) -> int: ...

    def numel(self) -> int: ...

    def itemsize(self) -> int: ...

    def is_contiguous(self) -> bool: ...

    @property
    def requires_grad(self) -> bool: ...

    @requires_grad.setter
    def requires_grad(self, arg: bool, /) -> None: ...

    @property
    def is_leaf(self) -> bool: ...

    @property
    def grad_fn(self) -> object: ...

    @property
    def is_cuda(self) -> bool: ...

    @property
    def grad(self) -> TensorBase | None: ...

    @grad.setter
    def grad(self, grad: TensorBase | None) -> None: ...

    def retain_grad(self) -> None: ...

    def detach(self) -> TensorBase: ...

    def clone(self) -> TensorBase: ...

    @overload
    def size(self) -> Size: ...

    @overload
    def size(self, arg: int, /) -> int: ...

    def view(self, *args) -> TensorBase: ...

    def reshape(self, *args) -> TensorBase: ...

    def expand(self, arg: Sequence[int], /) -> TensorBase: ...

    def as_strided(self, size: Sequence[int], stride: Sequence[int], storage_offset: int | None = None) -> TensorBase: ...

    def select(self, dim: int, index: int) -> TensorBase: ...

    def slice(self, dim: int, start: int, end: int, step: int = 1) -> TensorBase: ...

    def transpose(self, dim0: int, dim1: int) -> TensorBase: ...

    def t(self) -> TensorBase: ...

    def permute(self, dims: Sequence[int]) -> TensorBase: ...

    @overload
    def squeeze(self) -> TensorBase: ...

    @overload
    def squeeze(self, dim: int) -> TensorBase: ...

    def unsqueeze(self, dim: int) -> TensorBase: ...

    @overload
    def split(self, split_size: int, dim: int = 0) -> list[TensorBase]: ...

    @overload
    def split(self, split_sizes: Sequence[int], dim: int = 0) -> list[TensorBase]: ...

    def chunk(self, chunks: int, dim: int = 0) -> list[TensorBase]: ...

    def unbind(self, dim: int = 0) -> list[TensorBase]: ...

    @overload
    def sum(self, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def sum(self, dim: Sequence[int], keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def sum(self, dim: int, keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def mean(self, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def mean(self, dim: Sequence[int], keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def mean(self, dim: int, keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def prod(self, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def prod(self, dim: Sequence[int], keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def prod(self, dim: int, keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

    @overload
    def all(self) -> TensorBase: ...

    @overload
    def all(self, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...

    @overload
    def all(self, dim: int, keepdim: bool = False) -> TensorBase: ...

    @overload
    def any(self) -> TensorBase: ...

    @overload
    def any(self, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...

    @overload
    def any(self, dim: int, keepdim: bool = False) -> TensorBase: ...

    def argmax(self, dim: int | None = None, keepdim: bool = False) -> TensorBase: ...

    def argmin(self, dim: int | None = None, keepdim: bool = False) -> TensorBase: ...

    @overload
    def var(self, correction: int = 1) -> TensorBase: ...

    @overload
    def var(self, dim: Sequence[int], correction: int = 1, keepdim: bool = False) -> TensorBase: ...

    @overload
    def var(self, dim: int, correction: int = 1, keepdim: bool = False) -> TensorBase: ...

    @overload
    def std(self, correction: int = 1) -> TensorBase: ...

    @overload
    def std(self, dim: Sequence[int], correction: int = 1, keepdim: bool = False) -> TensorBase: ...

    @overload
    def std(self, dim: int, correction: int = 1, keepdim: bool = False) -> TensorBase: ...

    @overload
    def norm(self, p: float = 2.0) -> TensorBase: ...

    @overload
    def norm(self, dim: Sequence[int], p: float = 2.0, keepdim: bool = False) -> TensorBase: ...

    @overload
    def norm(self, dim: int, p: float = 2.0, keepdim: bool = False) -> TensorBase: ...

    @overload
    def max(self) -> TensorBase: ...

    @overload
    def max(self, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...

    @overload
    def max(self, dim: int, keepdim: bool = False) -> TensorBase: ...

    @overload
    def max(self) -> TensorBase: ...

    @overload
    def max(self, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...

    @overload
    def max(self, dim: int, keepdim: bool = False) -> TensorBase: ...

    @overload
    def min(self) -> TensorBase: ...

    @overload
    def min(self, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...

    @overload
    def min(self, dim: int, keepdim: bool = False) -> TensorBase: ...

    @overload
    def min(self) -> TensorBase: ...

    @overload
    def min(self, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...

    @overload
    def min(self, dim: int, keepdim: bool = False) -> TensorBase: ...

    @overload
    def pow(self, exponent: Scalar) -> TensorBase: ...

    @overload
    def pow(self, exponent: Scalar) -> TensorBase: ...

    @overload
    def pow(self, exponent: TensorBase) -> TensorBase: ...

    @overload
    def sqrt(self) -> TensorBase: ...

    @overload
    def sqrt(self) -> TensorBase: ...

    @overload
    def abs(self) -> TensorBase: ...

    @overload
    def abs(self) -> TensorBase: ...

    @overload
    def to(self, dtype: DType, non_blocking: bool = False, copy: bool = False) -> TensorBase: ...

    @overload
    def to(self, device: Device, non_blocking: bool = False, copy: bool = False) -> TensorBase: ...

    @overload
    def to(self, device: Device, dtype: DType, non_blocking: bool = False, copy: bool = False) -> TensorBase: ...

    def numpy(self) -> NDArray: ...

    def item(self) -> object: ...

    def __getitem__(self, arg: object, /) -> TensorBase: ...

    def __setitem__(self, arg0: object, arg1: object, /) -> None: ...

    @overload
    def __add__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __add__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __add__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __sub__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __sub__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __sub__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __mul__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __mul__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __mul__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __truediv__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __truediv__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __truediv__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __iadd__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __iadd__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __isub__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __isub__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __imul__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __imul__(self, arg: float, /) -> TensorBase: ...

    @overload
    def __itruediv__(self, arg: TensorBase, /) -> TensorBase: ...

    @overload
    def __itruediv__(self, arg: float, /) -> TensorBase: ...

    def __radd__(self, arg: float, /) -> TensorBase: ...

    def __rsub__(self, arg: float, /) -> TensorBase: ...

    def __rmul__(self, arg: float, /) -> TensorBase: ...

    @overload
    def add(self, other: TensorBase, alpha: Scalar = ...) -> TensorBase: ...

    @overload
    def add(self, other: Scalar, alpha: Scalar = ...) -> TensorBase: ...

    @overload
    def sub(self, other: TensorBase, alpha: Scalar = ...) -> TensorBase: ...

    @overload
    def sub(self, other: Scalar, alpha: Scalar = ...) -> TensorBase: ...

    @overload
    def mul(self, other: TensorBase) -> TensorBase: ...

    @overload
    def mul(self, other: Scalar) -> TensorBase: ...

    @overload
    def div(self, other: TensorBase) -> TensorBase: ...

    @overload
    def div(self, other: Scalar) -> TensorBase: ...

    def bernoulli(self) -> TensorBase: ...

    def poisson(self) -> TensorBase: ...

    def mm(self, other: TensorBase) -> TensorBase: ...

    def matmul(self, other: TensorBase) -> TensorBase: ...

    def __matmul__(self, other: TensorBase) -> TensorBase: ...

    def acos(self) -> TensorBase: ...

    def acosh(self) -> TensorBase: ...

    def angle(self) -> TensorBase: ...

    def asin(self) -> TensorBase: ...

    def asinh(self) -> TensorBase: ...

    def atan(self) -> TensorBase: ...

    def atanh(self) -> TensorBase: ...

    def ceil(self) -> TensorBase: ...

    def clamp(self, min: Scalar | None = None, max: Scalar | None = None) -> TensorBase: ...

    def cos(self) -> TensorBase: ...

    def cosh(self) -> TensorBase: ...

    def exp(self) -> TensorBase: ...

    def floor(self) -> TensorBase: ...

    def gelu(self) -> TensorBase: ...

    @overload
    def lerp(self, end: TensorBase, weight: Scalar) -> TensorBase: ...

    @overload
    def lerp(self, end: TensorBase, weight: TensorBase) -> TensorBase: ...

    def log(self) -> TensorBase: ...

    def neg(self) -> TensorBase: ...

    @overload
    def __pow__(self, exponent: Scalar) -> TensorBase: ...

    @overload
    def __pow__(self, exponent: TensorBase) -> TensorBase: ...

    def relu(self) -> TensorBase: ...

    def round(self) -> TensorBase: ...

    def rsqrt(self) -> TensorBase: ...

    def sigmoid(self) -> TensorBase: ...

    def silu(self) -> TensorBase: ...

    def sign(self) -> TensorBase: ...

    def sin(self) -> TensorBase: ...

    def sinh(self) -> TensorBase: ...

    def softmax(self, dim: int, dtype: DType = DType.undefined) -> TensorBase: ...

    def square(self) -> TensorBase: ...

    def tan(self) -> TensorBase: ...

    def tanh(self) -> TensorBase: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    @staticmethod
    def empty(size: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def zeros(shape: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def ones(shape: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def full(shape: Sequence[int], fill_value: Scalar, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def eye(n: int, m: int = -1, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @overload
    @staticmethod
    def arange(start: Scalar, end: Scalar, step: Scalar = ..., *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @overload
    @staticmethod
    def arange(end: Scalar, *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def rand(size: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def rand_like(input: TensorBase, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def randint(low: int, high: int, size: Sequence[int], *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def randint_like(input: TensorBase, low: int, high: int, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def randn(size: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def randn_like(input: TensorBase, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def randperm(n: int, *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def normal(mean: TensorBase, std: TensorBase) -> TensorBase: ...

    @staticmethod
    def linspace(start: Scalar, end: Scalar, steps: int, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def logspace(start: Scalar, end: Scalar, steps: int, base: float = 10.0, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

    @staticmethod
    def cat(tensors: Sequence[TensorBase], dim: int = 0) -> TensorBase: ...

    @staticmethod
    def stack(tensors: Sequence[TensorBase], dim: int = 0) -> TensorBase: ...

    @staticmethod
    def empty_like(input: TensorBase, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

    @staticmethod
    def zeros_like(input: TensorBase, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

    @staticmethod
    def ones_like(input: TensorBase, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

    @staticmethod
    def full_like(input: TensorBase, fill_value: Scalar, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

def tensor(data: object, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

def zeros(shape: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def ones(shape: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def eye(n: int, m: int = -1, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def empty(size: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def rand(size: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def rand_like(input: TensorBase, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

def randint(low: int, high: int, size: Sequence[int], *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def randint_like(input: TensorBase, low: int, high: int, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

def randn(size: Sequence[int], *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def randn_like(input: TensorBase, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

def randperm(n: int, *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def bernoulli(input: TensorBase) -> TensorBase: ...

def normal(mean: TensorBase, std: TensorBase) -> TensorBase: ...

def poisson(input: TensorBase) -> TensorBase: ...

def full(shape: Sequence[int], fill_value: Scalar, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

@overload
def arange(start: Scalar, end: Scalar, step: Scalar = 1, *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

@overload
def arange(end: Scalar, *, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def empty_like(input: TensorBase, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

def zeros_like(input: TensorBase, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

def ones_like(input: TensorBase, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

def full_like(input: TensorBase, fill_value: Scalar, dtype: DType | None = None, device: Device | None = None) -> TensorBase: ...

def mm(input: TensorBase, mat2: TensorBase) -> TensorBase: ...

def matmul(input: TensorBase, other: TensorBase) -> TensorBase: ...

def conv2d(input: TensorBase, weight: TensorBase, bias: TensorBase = ..., stride: Sequence[int] = [1, 1], padding: Sequence[int] = [0, 0], dilation: Sequence[int] = [1, 1], groups: int = 1) -> TensorBase: ...

def cat(tensors: Sequence[TensorBase], dim: int = 0) -> TensorBase: ...

def stack(tensors: Sequence[TensorBase], dim: int = 0) -> TensorBase: ...

def transpose(input: TensorBase, dim0: int, dim1: int) -> TensorBase: ...

def permute(input: TensorBase, dims: Sequence[int]) -> TensorBase: ...

@overload
def squeeze(input: TensorBase) -> TensorBase: ...

@overload
def squeeze(input: TensorBase, dim: int) -> TensorBase: ...

def unsqueeze(input: TensorBase, dim: int) -> TensorBase: ...

@overload
def split(input: TensorBase, split_size: int, dim: int = 0) -> list[TensorBase]: ...

@overload
def split(input: TensorBase, split_sizes: Sequence[int], dim: int = 0) -> list[TensorBase]: ...

def chunk(input: TensorBase, chunks: int, dim: int = 0) -> list[TensorBase]: ...

def t(input: TensorBase) -> TensorBase: ...

def linspace(start: Scalar, end: Scalar, steps: int, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def logspace(start: Scalar, end: Scalar, steps: int, base: float = 10.0, *, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...

def unbind(input: TensorBase, dim: int = 0) -> list[TensorBase]: ...

@overload
def sum(input: TensorBase, *, dtype: DType | None = None) -> TensorBase: ...

@overload
def sum(input: TensorBase, dim: Sequence[int], keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

@overload
def sum(input: TensorBase, dim: int, keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

@overload
def mean(input: TensorBase, *, dtype: DType | None = None) -> TensorBase: ...

@overload
def mean(input: TensorBase, dim: Sequence[int], keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

@overload
def mean(input: TensorBase, dim: int, keepdim: bool = False, *, dtype: DType | None = None) -> TensorBase: ...

def cuda_is_available() -> bool: ...
