from collections.abc import Iterator, Sequence
import enum
from typing import overload

from numpy.typing import NDArray

class DType(enum.Enum):
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    uint8 = 0

    int8 = 1

    int16 = 2

    int32 = 3

    int64 = 4

    uint16 = 5

    uint32 = 6

    uint64 = 7

    float32 = 8

    float64 = 9

    bool = 10

    complexfloat = 11

    complexdouble = 12

    undefined = 13

    numoptions = 14

uint8: DType = DType.uint8

int8: DType = DType.int8

int16: DType = DType.int16

int32: DType = DType.int32

int64: DType = DType.int64

uint16: DType = DType.uint16

uint32: DType = DType.uint32

uint64: DType = DType.uint64

float32: DType = DType.float32

float64: DType = DType.float64

bool: DType = DType.bool

complexfloat: DType = DType.complexfloat

complexdouble: DType = DType.complexdouble

undefined: DType = DType.undefined

numoptions: DType = DType.numoptions


class DeviceType(enum.Enum):
    CPU = 0

    CUDA = 1

CPU: DeviceType = DeviceType.CPU

CUDA: DeviceType = DeviceType.CUDA

class Device:
    @overload
    def __init__(self, type: DeviceType, index: int = -1) -> None: ...

    @overload
    def __init__(self, device: str) -> None: ...

    @overload
    def __init__(self, type: str, index: int) -> None: ...

    @property
    def type(self) -> str: ...

    @property
    def index(self) -> int: ...

    def is_cpu(self) -> bool: ...

    def is_cuda(self) -> bool: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __eq__(self, arg: Device, /) -> bool: ...

    def __ne__(self, arg: Device, /) -> bool: ...

class Scalar:
    @overload
    def __init__(self, arg: float, /) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

    @overload
    def __init__(self, arg: bool, /) -> None: ...

    def __repr__(self) -> str: ...

class Size:
    def __init__(self, arg: Sequence[int], /) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> int: ...

    def __iter__(self) -> Iterator[int]: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    @overload
    def __eq__(self, arg: Size, /) -> bool: ...

    @overload
    def __eq__(self, arg: tuple, /) -> bool: ...

    @overload
    def __eq__(self, arg: list, /) -> bool: ...

    def __ne__(self, arg: Size, /) -> bool: ...

class Generator:
    def __init__(self, seed: int = 0) -> None: ...

    def manual_seed(self, seed: int) -> int: ...

    def seed(self) -> int: ...

    def initial_seed(self) -> int: ...

    @property
    def device(self) -> Device: ...

def default_generator() -> Generator: ...

def manual_seed(seed: int) -> None: ...

def seed(seed: int) -> None: ...

def initial_seed() -> int: ...

class TensorBase:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, data: object, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> None: ...

    @property
    def shape(self) -> Size: ...

    @property
    def dtype(self) -> DType: ...

    @property
    def device(self) -> Device: ...

    @property
    def ndim(self) -> int: ...

    @property
    def data(self) -> TensorBase: ...

    def backward(self, gradient: TensorBase | None = None, retain_graph: bool = False, create_graph: bool = False) -> None: ...

    def dim(self) -> int: ...

    def numel(self) -> int: ...

    def itemsize(self) -> int: ...

    def is_contiguous(self) -> bool: ...

    @property
    def requires_grad(self) -> bool: ...

    @requires_grad.setter
    def requires_grad(self, arg: bool, /) -> None: ...

    @property
    def is_leaf(self) -> bool: ...

    @property
    def grad_fn(self) -> object: ...

    @property
    def is_cuda(self) -> bool: ...

    @property
    def grad(self) -> TensorBase | None: ...

    @grad.setter
    def grad(self, grad: TensorBase | None) -> None: ...

    def retain_grad(self) -> None: ...

    def detach(self) -> TensorBase: ...

    def clone(self) -> TensorBase: ...

    @overload
    def size(self) -> Size: ...

    @overload
    def size(self, arg: int, /) -> int: ...

    def view(self, *args) -> TensorBase: ...

    def reshape(self, *args) -> TensorBase: ...

    def expand(self, arg: Sequence[int], /) -> TensorBase: ...

    def as_strided(self, size: Sequence[int], stride: Sequence[int], storage_offset: int | None = None) -> TensorBase: ...

    def select(self, dim: int, index: int) -> TensorBase: ...

    def slice(self, dim: int, start: int, end: int, step: int = 1) -> TensorBase: ...
    
    # Manual operator overloads
    def __getitem__(self, arg: object, /) -> TensorBase: ...
    def __setitem__(self, arg0: object, arg1: object, /) -> None: ...
    
    # Arithmetic operators (manual overloads)
    @overload
    def __add__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __add__(self, arg: float, /) -> TensorBase: ...
    @overload
    def __add__(self, arg: float, /) -> TensorBase: ...
    
    @overload
    def __sub__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __sub__(self, arg: float, /) -> TensorBase: ...
    @overload
    def __sub__(self, arg: float, /) -> TensorBase: ...
    
    @overload
    def __mul__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __mul__(self, arg: float, /) -> TensorBase: ...
    @overload
    def __mul__(self, arg: float, /) -> TensorBase: ...
    
    @overload
    def __truediv__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __truediv__(self, arg: float, /) -> TensorBase: ...
    @overload
    def __truediv__(self, arg: float, /) -> TensorBase: ...

    # In-place operators
    @overload
    def __iadd__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __iadd__(self, arg: float, /) -> TensorBase: ...
    @overload
    def __isub__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __isub__(self, arg: float, /) -> TensorBase: ...
    @overload
    def __imul__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __imul__(self, arg: float, /) -> TensorBase: ...
    @overload
    def __itruediv__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __itruediv__(self, arg: float, /) -> TensorBase: ...
    
    # Reverse operators
    def __radd__(self, arg: float, /) -> TensorBase: ...
    def __rsub__(self, arg: float, /) -> TensorBase: ...
    def __rmul__(self, arg: float, /) -> TensorBase: ...
    
    @overload
    def __matmul__(self, arg: TensorBase, /) -> TensorBase: ...
    @overload
    def __matmul__(self, other: TensorBase) -> TensorBase: ...
    
    @overload
    def __pow__(self, arg: object, /) -> TensorBase: ...
    @overload
    def __pow__(self, exponent: Scalar) -> TensorBase: ...
    @overload
    def __pow__(self, exponent: TensorBase) -> TensorBase: ...
    
    def __rpow__(self, arg: object, /) -> TensorBase: ...
    
    # Comparison operators
    def __eq__(self, arg: object, /) -> TensorBase: ...
    def __ne__(self, arg: object, /) -> TensorBase: ...
    def __lt__(self, arg: object, /) -> TensorBase: ...
    def __le__(self, arg: object, /) -> TensorBase: ...
    def __gt__(self, arg: object, /) -> TensorBase: ...
    def __ge__(self, arg: object, /) -> TensorBase: ...
    
    def numpy(self) -> NDArray: ...
    def item(self) -> object: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

    # Generated methods will be inserted here
    def add(other: TensorBase, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def add(other: Scalar, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def add_(other: TensorBase, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def add_(other: Scalar, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def sub(other: TensorBase, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def sub(other: Scalar, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def sub_(other: TensorBase, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def sub_(other: Scalar, alpha: Scalar = Scalar(1)) -> TensorBase: ...
    def mul(other: TensorBase) -> TensorBase: ...
    def mul(other: Scalar) -> TensorBase: ...
    def mul_(other: TensorBase) -> TensorBase: ...
    def mul_(other: Scalar) -> TensorBase: ...
    def div(other: TensorBase) -> TensorBase: ...
    def div(other: Scalar) -> TensorBase: ...
    def div_(other: TensorBase) -> TensorBase: ...
    def div_(other: Scalar) -> TensorBase: ...
    def mm(other: TensorBase) -> TensorBase: ...
    def matmul(other: TensorBase) -> TensorBase: ...
    def eq(other: TensorBase) -> TensorBase: ...
    def eq(other: Scalar) -> TensorBase: ...
    def ne(other: TensorBase) -> TensorBase: ...
    def ne(other: Scalar) -> TensorBase: ...
    def lt(other: TensorBase) -> TensorBase: ...
    def lt(other: Scalar) -> TensorBase: ...
    def le(other: TensorBase) -> TensorBase: ...
    def le(other: Scalar) -> TensorBase: ...
    def gt(other: TensorBase) -> TensorBase: ...
    def gt(other: Scalar) -> TensorBase: ...
    def ge(other: TensorBase) -> TensorBase: ...
    def ge(other: Scalar) -> TensorBase: ...
    def copy_(src: TensorBase) -> TensorBase: ...
    def view(shape: Sequence[int]) -> TensorBase: ...
    def fill_(value: Scalar) -> TensorBase: ...
    def transpose(dim0: int, dim1: int) -> TensorBase: ...
    def t() -> TensorBase: ...
    def permute(dims: Sequence[int]) -> TensorBase: ...
    def squeeze() -> TensorBase: ...
    def squeeze(dim: int) -> TensorBase: ...
    def unsqueeze(dim: int) -> TensorBase: ...
    def split(split_size: int, dim: int = 0) -> list[TensorBase]: ...
    def split(split_sizes: Sequence[int], dim: int = 0) -> list[TensorBase]: ...
    def chunk(chunks: int, dim: int = 0) -> list[TensorBase]: ...
    def reshape(shape: Sequence[int]) -> TensorBase: ...
    def unbind(dim: int = 0) -> list[TensorBase]: ...
    def bernoulli() -> TensorBase: ...
    def abs() -> TensorBase: ...
    def acos() -> TensorBase: ...
    def acosh() -> TensorBase: ...
    def angle() -> TensorBase: ...
    def asin() -> TensorBase: ...
    def asinh() -> TensorBase: ...
    def atan() -> TensorBase: ...
    def poisson() -> TensorBase: ...
    def atanh() -> TensorBase: ...
    def ceil() -> TensorBase: ...
    def clamp(min: Scalar | None = None, max: Scalar | None = None) -> TensorBase: ...
    def cos() -> TensorBase: ...
    def cosh() -> TensorBase: ...
    def exp() -> TensorBase: ...
    def floor() -> TensorBase: ...
    def lerp(end: TensorBase, weight: Scalar) -> TensorBase: ...
    def lerp(end: TensorBase, weight: TensorBase) -> TensorBase: ...
    def log() -> TensorBase: ...
    def neg() -> TensorBase: ...
    def pow(exponent: Scalar) -> TensorBase: ...
    def pow(exponent: TensorBase) -> TensorBase: ...
    def round() -> TensorBase: ...
    def rsqrt() -> TensorBase: ...
    def sigmoid() -> TensorBase: ...
    def sign() -> TensorBase: ...
    def sin() -> TensorBase: ...
    def sinh() -> TensorBase: ...
    def softmax(dim: int, dtype: DType = DType.undefined) -> TensorBase: ...
    def sqrt() -> TensorBase: ...
    def square() -> TensorBase: ...
    def tan() -> TensorBase: ...
    def tanh() -> TensorBase: ...
    def relu() -> TensorBase: ...
    def gelu() -> TensorBase: ...
    def silu() -> TensorBase: ...
    def sum(dtype: DType = DType.undefined) -> TensorBase: ...
    def sum(dim: Sequence[int], keepdim: bool = False, dtype: DType = DType.undefined) -> TensorBase: ...
    def mean(dtype: DType = DType.undefined) -> TensorBase: ...
    def mean(dim: Sequence[int], keepdim: bool = False, dtype: DType = DType.undefined) -> TensorBase: ...
    def max() -> TensorBase: ...
    def max(dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
    def min() -> TensorBase: ...
    def min(dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
    def prod(dtype: DType = DType.undefined) -> TensorBase: ...
    def prod(dim: Sequence[int], keepdim: bool = False, dtype: DType = DType.undefined) -> TensorBase: ...
    def argmax(dim: int | None = None, keepdim: bool = False) -> TensorBase: ...
    def argmin(dim: int | None = None, keepdim: bool = False) -> TensorBase: ...
    def all() -> TensorBase: ...
    def all(dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
    def any() -> TensorBase: ...
    def any(dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
    def var(correction: int = 1) -> TensorBase: ...
    def var(dim: Sequence[int], correction: int = 1, keepdim: bool = False) -> TensorBase: ...
    def std(correction: int = 1) -> TensorBase: ...
    def std(dim: Sequence[int], correction: int = 1, keepdim: bool = False) -> TensorBase: ...
    def norm(p: float = 2.0) -> TensorBase: ...
    def norm(dim: Sequence[int], p: float = 2.0, keepdim: bool = False) -> TensorBase: ...
    def exponential_(lambd: float = 1.0) -> TensorBase: ...
    def geometric_(p: float) -> TensorBase: ...
    def log_normal_(mean: float = 1.0, std: float = 2.0) -> TensorBase: ...
    def normal_(mean: float = 0.0, std: float = 1.0) -> TensorBase: ...
    def random_(low: int = 0, high: int = 0) -> TensorBase: ...
    def uniform_(from_: float = 0.0, to: float = 1.0) -> TensorBase: ...
    def bernoulli_() -> TensorBase: ...
    def cauchy_(median: float = 0.0, sigma: float = 1.0) -> TensorBase: ...
    def masked_select(mask: TensorBase) -> TensorBase: ...
    def zero_() -> TensorBase: ...

# Static factory methods (manual for now, could be generated if in yaml)
def tensor(data: object, *, dtype: DType | None = None, device: Device | None = None, requires_grad: bool = False) -> TensorBase: ...

# Generated functions will be inserted here
def conv2d(input: TensorBase, weight: TensorBase, bias: TensorBase = {}, stride: Sequence[int] = {1, 1}, padding: Sequence[int] = {0, 0}, dilation: Sequence[int] = {1, 1}, groups: int = 1) -> TensorBase: ...
def mm(self: TensorBase, other: TensorBase) -> TensorBase: ...
def matmul(self: TensorBase, other: TensorBase) -> TensorBase: ...
def eq(self: TensorBase, other: TensorBase) -> TensorBase: ...
def eq(self: TensorBase, other: Scalar) -> TensorBase: ...
def ne(self: TensorBase, other: TensorBase) -> TensorBase: ...
def ne(self: TensorBase, other: Scalar) -> TensorBase: ...
def lt(self: TensorBase, other: TensorBase) -> TensorBase: ...
def lt(self: TensorBase, other: Scalar) -> TensorBase: ...
def le(self: TensorBase, other: TensorBase) -> TensorBase: ...
def le(self: TensorBase, other: Scalar) -> TensorBase: ...
def gt(self: TensorBase, other: TensorBase) -> TensorBase: ...
def gt(self: TensorBase, other: Scalar) -> TensorBase: ...
def ge(self: TensorBase, other: TensorBase) -> TensorBase: ...
def ge(self: TensorBase, other: Scalar) -> TensorBase: ...
def transpose(self: TensorBase, dim0: int, dim1: int) -> TensorBase: ...
def t(self: TensorBase) -> TensorBase: ...
def permute(self: TensorBase, dims: Sequence[int]) -> TensorBase: ...
def squeeze(self: TensorBase) -> TensorBase: ...
def squeeze(self: TensorBase, dim: int) -> TensorBase: ...
def unsqueeze(self: TensorBase, dim: int) -> TensorBase: ...
def cat(tensors: Sequence[TensorBase], dim: int = 0) -> TensorBase: ...
def stack(tensors: Sequence[TensorBase], dim: int = 0) -> TensorBase: ...
def split(self: TensorBase, split_size: int, dim: int = 0) -> list[TensorBase]: ...
def split(self: TensorBase, split_sizes: Sequence[int], dim: int = 0) -> list[TensorBase]: ...
def chunk(self: TensorBase, chunks: int, dim: int = 0) -> list[TensorBase]: ...
def reshape(self: TensorBase, shape: Sequence[int]) -> TensorBase: ...
def unbind(self: TensorBase, dim: int = 0) -> list[TensorBase]: ...
def rand(size: Sequence[int], dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def rand_like(self: TensorBase, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def randint(low: int, high: int, size: Sequence[int], dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def randint_like(self: TensorBase, low: int, high: int, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def randn(size: Sequence[int], dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def randn_like(self: TensorBase, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def randperm(n: int, dtype: DType = DType.int64, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def bernoulli(self: TensorBase) -> TensorBase: ...
def normal(mean: TensorBase, std: TensorBase) -> TensorBase: ...
def abs(self: TensorBase) -> TensorBase: ...
def acos(self: TensorBase) -> TensorBase: ...
def acosh(self: TensorBase) -> TensorBase: ...
def angle(self: TensorBase) -> TensorBase: ...
def asin(self: TensorBase) -> TensorBase: ...
def asinh(self: TensorBase) -> TensorBase: ...
def atan(self: TensorBase) -> TensorBase: ...
def poisson(self: TensorBase) -> TensorBase: ...
def atanh(self: TensorBase) -> TensorBase: ...
def ceil(self: TensorBase) -> TensorBase: ...
def clamp(self: TensorBase, min: Scalar | None = None, max: Scalar | None = None) -> TensorBase: ...
def cos(self: TensorBase) -> TensorBase: ...
def cosh(self: TensorBase) -> TensorBase: ...
def exp(self: TensorBase) -> TensorBase: ...
def floor(self: TensorBase) -> TensorBase: ...
def lerp(self: TensorBase, end: TensorBase, weight: Scalar) -> TensorBase: ...
def lerp(self: TensorBase, end: TensorBase, weight: TensorBase) -> TensorBase: ...
def log(self: TensorBase) -> TensorBase: ...
def neg(self: TensorBase) -> TensorBase: ...
def pow(self: TensorBase, exponent: Scalar) -> TensorBase: ...
def pow(self: TensorBase, exponent: TensorBase) -> TensorBase: ...
def round(self: TensorBase) -> TensorBase: ...
def rsqrt(self: TensorBase) -> TensorBase: ...
def sigmoid(self: TensorBase) -> TensorBase: ...
def sign(self: TensorBase) -> TensorBase: ...
def sin(self: TensorBase) -> TensorBase: ...
def sinh(self: TensorBase) -> TensorBase: ...
def softmax(self: TensorBase, dim: int, dtype: DType = DType.undefined) -> TensorBase: ...
def sqrt(self: TensorBase) -> TensorBase: ...
def square(self: TensorBase) -> TensorBase: ...
def tan(self: TensorBase) -> TensorBase: ...
def tanh(self: TensorBase) -> TensorBase: ...
def relu(self: TensorBase) -> TensorBase: ...
def gelu(self: TensorBase) -> TensorBase: ...
def silu(self: TensorBase) -> TensorBase: ...
def empty(size: Sequence[int], dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def full(size: Sequence[int], fill_value: Scalar, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def zeros(size: Sequence[int], dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def ones(size: Sequence[int], dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def eye(n: int, m: int = -1, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def arange(start: Scalar, end: Scalar, step: Scalar = Scalar(1), dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def arange(end: Scalar, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def linspace(start: Scalar, end: Scalar, steps: int, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def logspace(start: Scalar, end: Scalar, steps: int, base: float = 10.0, dtype: DType = DType.float32, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def sum(self: TensorBase, dtype: DType = DType.undefined) -> TensorBase: ...
def sum(self: TensorBase, dim: Sequence[int], keepdim: bool = False, dtype: DType = DType.undefined) -> TensorBase: ...
def mean(self: TensorBase, dtype: DType = DType.undefined) -> TensorBase: ...
def mean(self: TensorBase, dim: Sequence[int], keepdim: bool = False, dtype: DType = DType.undefined) -> TensorBase: ...
def max(self: TensorBase) -> TensorBase: ...
def max(self: TensorBase, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
def min(self: TensorBase) -> TensorBase: ...
def min(self: TensorBase, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
def prod(self: TensorBase, dtype: DType = DType.undefined) -> TensorBase: ...
def prod(self: TensorBase, dim: Sequence[int], keepdim: bool = False, dtype: DType = DType.undefined) -> TensorBase: ...
def argmax(self: TensorBase, dim: int | None = None, keepdim: bool = False) -> TensorBase: ...
def argmin(self: TensorBase, dim: int | None = None, keepdim: bool = False) -> TensorBase: ...
def all(self: TensorBase) -> TensorBase: ...
def all(self: TensorBase, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
def any(self: TensorBase) -> TensorBase: ...
def any(self: TensorBase, dim: Sequence[int], keepdim: bool = False) -> TensorBase: ...
def var(self: TensorBase, correction: int = 1) -> TensorBase: ...
def var(self: TensorBase, dim: Sequence[int], correction: int = 1, keepdim: bool = False) -> TensorBase: ...
def std(self: TensorBase, correction: int = 1) -> TensorBase: ...
def std(self: TensorBase, dim: Sequence[int], correction: int = 1, keepdim: bool = False) -> TensorBase: ...
def norm(self: TensorBase, p: float = 2.0) -> TensorBase: ...
def norm(self: TensorBase, dim: Sequence[int], p: float = 2.0, keepdim: bool = False) -> TensorBase: ...
def empty_like(self: TensorBase, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def zeros_like(self: TensorBase, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def ones_like(self: TensorBase, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def full_like(self: TensorBase, fill_value: Scalar, dtype: DType = DType.undefined, device: Device = ..., requires_grad: bool = False) -> TensorBase: ...
def masked_select(self: TensorBase, mask: TensorBase) -> TensorBase: ...
