# Generated by tools/codegen/gen.py
# Do not edit directly

from ._C import *

def add(input, other, alpha=Scalar(1)):
    return input.add(other=other, alpha=alpha)

def add_(input, other, alpha=Scalar(1)):
    return input.add_(other=other, alpha=alpha)

def sub(input, other, alpha=Scalar(1)):
    return input.sub(other=other, alpha=alpha)

def sub_(input, other, alpha=Scalar(1)):
    return input.sub_(other=other, alpha=alpha)

def mul(input, other):
    return input.mul(other=other)

def mul_(input, other):
    return input.mul_(other=other)

def div(input, other):
    return input.div(other=other)

def div_(input, other):
    return input.div_(other=other)

def mm(input, other):
    return input.mm(other=other)

def matmul(input, other):
    return input.matmul(other=other)

def eq(input, other):
    return input.eq(other=other)

def ne(input, other):
    return input.ne(other=other)

def lt(input, other):
    return input.lt(other=other)

def le(input, other):
    return input.le(other=other)

def gt(input, other):
    return input.gt(other=other)

def ge(input, other):
    return input.ge(other=other)

def copy_(input, src):
    return input.copy_(src=src)

def view(input, shape):
    return input.view(shape=shape)

def fill_(input, value):
    return input.fill_(value=value)

def transpose(input, dim0, dim1):
    return input.transpose(dim0=dim0, dim1=dim1)

def t(input):
    return input.t()

def permute(input, dims):
    return input.permute(dims=dims)

def squeeze(input):
    return input.squeeze()

def unsqueeze(input, dim):
    return input.unsqueeze(dim=dim)

def split(input, split_size, dim=0):
    return input.split(split_size=split_size, dim=dim)

def chunk(input, chunks, dim=0):
    return input.chunk(chunks=chunks, dim=dim)

def reshape(input, shape):
    return input.reshape(shape=shape)

def unbind(input, dim=0):
    return input.unbind(dim=dim)

def bernoulli(input):
    return input.bernoulli()

def abs(input):
    return input.abs()

def acos(input):
    return input.acos()

def acosh(input):
    return input.acosh()

def angle(input):
    return input.angle()

def asin(input):
    return input.asin()

def asinh(input):
    return input.asinh()

def atan(input):
    return input.atan()

def poisson(input):
    return input.poisson()

def atanh(input):
    return input.atanh()

def ceil(input):
    return input.ceil()

def clamp(input, min=None, max=None):
    return input.clamp(min=min, max=max)

def cos(input):
    return input.cos()

def cosh(input):
    return input.cosh()

def exp(input):
    return input.exp()

def floor(input):
    return input.floor()

def lerp(input, end, weight):
    return input.lerp(end=end, weight=weight)

def log(input):
    return input.log()

def neg(input):
    return input.neg()

def pow(input, exponent):
    return input.pow(exponent=exponent)

def round(input):
    return input.round()

def rsqrt(input):
    return input.rsqrt()

def sigmoid(input):
    return input.sigmoid()

def sign(input):
    return input.sign()

def sin(input):
    return input.sin()

def sinh(input):
    return input.sinh()

def softmax(input, dim, dtype=DType.undefined):
    return input.softmax(dim=dim, dtype=dtype)

def sqrt(input):
    return input.sqrt()

def square(input):
    return input.square()

def tan(input):
    return input.tan()

def tanh(input):
    return input.tanh()

def relu(input):
    return input.relu()

def gelu(input):
    return input.gelu()

def silu(input):
    return input.silu()

def sum(input, dtype=DType.undefined):
    return input.sum(dtype=dtype)

def mean(input, dtype=DType.undefined):
    return input.mean(dtype=dtype)

def max(input):
    return input.max()

def min(input):
    return input.min()

def prod(input, dtype=DType.undefined):
    return input.prod(dtype=dtype)

def argmax(input, dim=None, keepdim=False):
    return input.argmax(dim=dim, keepdim=keepdim)

def argmin(input, dim=None, keepdim=False):
    return input.argmin(dim=dim, keepdim=keepdim)

def all(input):
    return input.all()

def any(input):
    return input.any()

def var(input, correction=1):
    return input.var(correction=correction)

def std(input, correction=1):
    return input.std(correction=correction)

def norm(input, p=2.0):
    return input.norm(p=p)

def exponential_(input, lambd=1.0):
    return input.exponential_(lambd=lambd)

def geometric_(input, p):
    return input.geometric_(p=p)

def log_normal_(input, mean=1.0, std=2.0):
    return input.log_normal_(mean=mean, std=std)

def normal_(input, mean=0.0, std=1.0):
    return input.normal_(mean=mean, std=std)

def random_(input, low=0, high=0):
    return input.random_(low=low, high=high)

def uniform_(input, from_=0.0, to=1.0):
    return input.uniform_(from_=from_, to=to)

def bernoulli_(input):
    return input.bernoulli_()

def cauchy_(input, median=0.0, sigma=1.0):
    return input.cauchy_(median=median, sigma=sigma)

def masked_select(input, mask):
    return input.masked_select(mask=mask)

def zero_(input):
    return input.zero_()
