import yaml
import os
import re
import argparse
import copy

import codegen_utils

# Type mapping from YAML schema to C++ signature
TYPE_MAP = {
    'int64_t[]': 'const std::vector<int64_t>&',
    'Tensor[]': 'const std::vector<Tensor>&',
    'DType': 'DType',
    'Device': 'Device',
    'double': 'double',
    'bool': 'bool',
    'Scalar': 'Scalar',
    'Scalar?': 'std::optional<Scalar>',
    'Tensor': 'const Tensor&',
    'Tensor(a!)': 'Tensor&',
    'Scalar?': 'std::optional<Scalar>',
    'int64_t?': 'std::optional<int64_t>',
}

# Type mapping for DispatchStub template arguments
# Usually we pass by value to python adapter often easier, or stick to const ref
STUB_TYPE_MAP = {
    'int64_t[]': 'const std::vector<int64_t>&',
    'Tensor[]': 'const std::vector<Tensor>&',
    'DType': 'DType',
    'Device': 'Device',
    'double': 'double',
    'bool': 'bool',
    'Scalar': 'Scalar',
    'Scalar?': 'std::optional<Scalar>',
    'Tensor': 'const Tensor&',
    'Tensor(a!)': 'Tensor&',
    'Scalar?': 'std::optional<Scalar>',
    'int64_t?': 'std::optional<int64_t>',
}

def default_handler(type_str, default):
    if default == 'Float32': return 'DType::Float32'
    if default == 'CPU': return 'Device(DeviceType::CPU)'
    if default == 'Int64': return 'DType::Int64'
    if default == 'Undefined': return 'DType::Undefined'
    if default == 'None': return 'std::nullopt'
    if type_str == 'Scalar' and re.match(r'^-?\d+(\.\d+)?$', default):
        return f'Scalar({default})'
    return default

def parse_func(func_str):
    # Use shared util
    # Adjust return type map for Tensor(a!) -> Tensor& manually or via map
    # The utils_parse_func uses the map for return type too.
    # TYPE_MAP has 'Tensor(a!)': 'Tensor&'
    
    # We need to map 'Tensor' return type to 'Tensor' (value), not 'const Tensor&'
    # But TYPE_MAP maps 'Tensor' to 'const Tensor&' for arguments.
    # So we should pass a specific map for return types or handle it.
    
    # Let's just use TYPE_MAP and fix return type if needed.
    # Actually, utils_parse_func uses type_map for return type.
    # 'Tensor' in return type should be 'Tensor', not 'const Tensor&'.
    
    # Let's use a copy of TYPE_MAP for args
    arg_type_map = TYPE_MAP.copy()
    
    f = codegen_utils.parse_func(func_str, arg_type_map, default_handler)
    
    if f['schema_return_type'] == 'Tensor':
        f['return_type'] = 'Tensor'
    if f['schema_return_type'] == 'Tensor(a!)':
        f['return_type'] = 'Tensor&'
    elif f['schema_return_type'] == 'Tensor[]':
        f['return_type'] = 'std::vector<Tensor>'
        
    # Add stub_type
    for arg in f['args']:
        arg['stub_type'] = STUB_TYPE_MAP.get(arg['type'], arg['type'])
        
    return f

def generate_header(funcs):
    lines = []
    lines.append("// Generated by tools/codegen/gen.py")
    lines.append("#pragma once")
    lines.append("// #include <vector> // Provided by Tensor.h")
    lines.append("// #include <optional> // Provided by Tensor.h")
    lines.append("// #include \"tensorplay/core/DType.h\" // Provided by Tensor.h")
    lines.append("// #include \"tensorplay/core/Device.h\" // Provided by Tensor.h")
    lines.append("// #include \"tensorplay/core/Scalar.h\" // Provided by Tensor.h")
    lines.append("")
    lines.append("// Forward declaration")
    lines.append("// This file is intended to be included inside the Tensor class definition")
    lines.append("// or used where Tensor is defined.")
    lines.append("")
    
    for f in funcs:
        sig = f['return_type'] + " " + f['name'] + "("
        arg_strs = []
        is_const_method = False
        if f['variants'] == 'method':
             self_arg = next((arg for arg in f['args'] if arg['name'] == 'self'), None)
             if self_arg and '!' not in self_arg['type']:
                 is_const_method = True

        for arg in f['args']:
            # Skip 'self' argument for methods
            if f['variants'] == 'method' and arg['name'] == 'self':
                continue
                
            s = f"{arg['cpp_type']} {arg['name']}"
            if arg['default']:
                s += f" = {arg['default']}"
            arg_strs.append(s)
        sig += ", ".join(arg_strs) + ")"
        
        if is_const_method:
            sig += " const"
        
        if f['variants'] == 'function':
            lines.append(f"    static {sig};")
        else:
            lines.append(f"    {sig};")
        lines.append("")
        
    return "\n".join(lines)

def generate_cpp(funcs):
    lines = []
    lines.append("// Generated by tools/codegen/gen.py")
    lines.append("#include \"tensorplay/core/Tensor.h\"")
    lines.append("#include \"tensorplay/core/Dispatcher.h\"")
    lines.append("#include \"tensorplay/core/Exception.h\"")
    lines.append("")
    lines.append("namespace tensorplay {")
    lines.append("")
    
    for f in funcs:
        # Implementation signature (no defaults)
        sig = f['return_type'] + " Tensor::" + f['name'] + "("
        arg_strs = []
        is_const_method = False
        if f['variants'] == 'method':
             self_arg = next((arg for arg in f['args'] if arg['name'] == 'self'), None)
             if self_arg and '!' not in self_arg['type']:
                 is_const_method = True

        for arg in f['args']:
            # Skip 'self' argument for methods
            if f['variants'] == 'method' and arg['name'] == 'self':
                continue
                
            s = f"{arg['cpp_type']} {arg['name']}"
            arg_strs.append(s)
        sig += ", ".join(arg_strs) + ")"
        
        if is_const_method:
            sig += " const"
        
        lines.append(sig + " {")
        
        # Body
        # 1. Validation (if any)
        if f['name'] == 'copy_':
             lines.append('    if (!impl_ || !src.impl_) TP_THROW(RuntimeError, "Tensor not defined");')
             lines.append('    if (this->shape() != src.shape()) {')
             lines.append('        TP_THROW(RuntimeError, "copy_(): shapes mismatch (broadcasting not yet supported)");')
             lines.append('    }')
        
        # 2. Compute Dispatch Key
        # If explicit device arg exists, use it. Else use self.device() or default.
        # For factories, device is usually passed.
        # For methods, use self.device().
        
        dispatch_key_source = "Device(DeviceType::CPU)" # Default fallback
        
        # Find 'device' arg
        device_arg = next((arg for arg in f['args'] if arg['name'] == 'device'), None)
        
        if device_arg:
            dispatch_key_source = "device"
        elif f['variants'] == 'method':
            dispatch_key_source = "device()" # this->device()
        
        lines.append(f"    DispatchKey key = computeDispatchKey({dispatch_key_source});")
        
        # 3. Call DispatchStub
        # DispatchStub<Return, Args...>::call(op_name, key, args...)
        
        template_args = [f['return_type']]
        # Use full func_name (e.g. "add.Tensor") for dispatch to support overloads
        call_args = [f'"{f["func_name"]}"', "key"]
        
        for arg in f['args']:
            template_args.append(arg['stub_type'])
            # Pass *this for self if it's a method and argument is 'self'
            if f['variants'] == 'method' and arg['name'] == 'self':
                call_args.append("*this")
            else:
                call_args.append(arg['name'])
                
        template_str = ", ".join(template_args)
        call_str = ", ".join(call_args)
        
        lines.append(f"    return DispatchStub<{template_str}>::call({call_str});")
        lines.append("}")
        lines.append("")
        
    lines.append("} // namespace tensorplay")
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yaml', required=True, help='Path to native_functions.yaml')
    parser.add_argument('--out_dir', required=True, help='Output directory')
    args = parser.parse_args()
    
    with open(args.yaml, 'r') as f:
        data = yaml.safe_load(f)
        
    if data is None:
        data = []
        
    funcs = []
    for item in data:
        base_f = parse_func(item['func'])
        variants_str = item.get('variants', 'function')
        variants = [v.strip() for v in variants_str.split(',')]
        
        for v in variants:
            f = copy.deepcopy(base_f)
            f['variants'] = v
            funcs.append(f)
        
    if not os.path.exists(args.out_dir):
        os.makedirs(args.out_dir)
        
    header_path = os.path.join(args.out_dir, "TensorGenerated.h")
    cpp_path = os.path.join(args.out_dir, "TensorGenerated.cpp")
    
    with open(header_path, 'w') as f:
        f.write(generate_header(funcs))
        
    with open(cpp_path, 'w') as f:
        f.write(generate_cpp(funcs))
        
    print(f"Generated {header_path} and {cpp_path}")

if __name__ == "__main__":
    main()
