import yaml
import os
import re
import argparse

# Type mapping from YAML schema to C++ signature
TYPE_MAP = {
    'int64_t[]': 'const std::vector<int64_t>&',
    'DType': 'DType',
    'Device': 'Device',
    'double': 'double',
    'bool': 'bool',
    'Scalar': 'Scalar',
    'Tensor': 'const Tensor&',
    'Tensor(a!)': 'Tensor&',
}

# Type mapping for DispatchStub template arguments
# Usually we pass by value or const ref.
STUB_TYPE_MAP = {
    'int64_t[]': 'const std::vector<int64_t>&',
    'DType': 'DType',
    'Device': 'Device',
    'double': 'double',
    'bool': 'bool',
    'Scalar': 'Scalar',
    'Tensor': 'const Tensor&',
    'Tensor(a!)': 'Tensor&',
}

def parse_args(arg_str):
    # Split by comma, handling nested parens if necessary (not needed for this simple schema)
    args = []
    if not arg_str:
        return args
    
    # Simple split by comma
    parts = [p.strip() for p in arg_str.split(',')]
    for p in parts:
        # Parse "Type name=Default"
        default = None
        if '=' in p:
            p, default = p.split('=', 1)
            p = p.strip()
            default = default.strip()
            # Handle enum defaults
            if default == 'Float32': default = 'DType::Float32'
            if default == 'CPU': default = 'Device(DeviceType::CPU)'
            if default == 'Int64': default = 'DType::Int64'
        
        # Parse "Type name"
        # Handle "Tensor(a!) self"
        if ' ' not in p:
            raise ValueError(f"Invalid arg: {p}")
        
        type_str, name = p.rsplit(' ', 1)
        type_str = type_str.strip()
        name = name.strip()
        
        cpp_type = TYPE_MAP.get(type_str, type_str)
        stub_type = STUB_TYPE_MAP.get(type_str, type_str)
        
        # Handle Scalar defaults (explicit construction)
        if default and type_str == 'Scalar' and re.match(r'^-?\d+(\.\d+)?$', default):
            default = f'Scalar({default})'
        
        args.append({
            'name': name,
            'type': type_str,
            'cpp_type': cpp_type,
            'stub_type': stub_type,
            'default': default
        })
    return args

def parse_func(func_str):
    # "name(args) -> Return"
    match = re.match(r'(\w+)\((.*)\)\s*->\s*(.*)', func_str)
    if not match:
        raise ValueError(f"Invalid func: {func_str}")
    
    name = match.group(1)
    args_str = match.group(2)
    return_type_str = match.group(3).strip()
    
    # Handle Return type
    # Tensor(a!) -> Tensor&
    if return_type_str == 'Tensor(a!)':
        return_type = 'Tensor&'
    elif return_type_str == 'Tensor':
        return_type = 'Tensor'
    else:
        return_type = return_type_str
        
    args = parse_args(args_str)
    
    return {
        'name': name,
        'args': args,
        'return_type': return_type,
        'schema_return_type': return_type_str
    }

def generate_header(funcs):
    lines = []
    lines.append("// Generated by tools/codegen/gen.py")
    lines.append("#pragma once")
    lines.append("// #include <vector> // Provided by Tensor.h")
    lines.append("// #include <optional> // Provided by Tensor.h")
    lines.append("// #include \"tensorplay/core/DType.h\" // Provided by Tensor.h")
    lines.append("// #include \"tensorplay/core/Device.h\" // Provided by Tensor.h")
    lines.append("// #include \"tensorplay/core/Scalar.h\" // Provided by Tensor.h")
    lines.append("")
    lines.append("// Forward declaration")
    lines.append("// This file is intended to be included inside the Tensor class definition")
    lines.append("// or used where Tensor is defined.")
    lines.append("")
    
    for f in funcs:
        sig = f['return_type'] + " " + f['name'] + "("
        arg_strs = []
        for arg in f['args']:
            # Skip 'self' argument for methods
            if f['variants'] == 'method' and arg['name'] == 'self':
                continue
                
            s = f"{arg['cpp_type']} {arg['name']}"
            if arg['default']:
                s += f" = {arg['default']}"
            arg_strs.append(s)
        sig += ", ".join(arg_strs) + ")"
        
        if f['variants'] == 'function':
            lines.append(f"    static {sig};")
        else:
            lines.append(f"    {sig};")
        lines.append("")
        
    return "\n".join(lines)

def generate_cpp(funcs):
    lines = []
    lines.append("// Generated by tools/codegen/gen.py")
    lines.append("#include \"tensorplay/core/Tensor.h\"")
    lines.append("#include \"tensorplay/core/Dispatcher.h\"")
    lines.append("")
    lines.append("namespace tensorplay {")
    lines.append("")
    
    for f in funcs:
        # Implementation signature (no defaults)
        sig = f['return_type'] + " Tensor::" + f['name'] + "("
        arg_strs = []
        for arg in f['args']:
            # Skip 'self' argument for methods
            if f['variants'] == 'method' and arg['name'] == 'self':
                continue
                
            s = f"{arg['cpp_type']} {arg['name']}"
            arg_strs.append(s)
        sig += ", ".join(arg_strs) + ")"
        
        lines.append(sig + " {")
        
        # Body
        # 1. Validation (if any)
        if f['name'] == 'copy_':
             lines.append('    if (!impl_ || !src.impl_) throw std::runtime_error("Tensor not defined");')
             lines.append('    if (this->shape() != src.shape()) {')
             lines.append('        throw std::runtime_error("copy_(): shapes mismatch (broadcasting not yet supported)");')
             lines.append('    }')
        
        # 2. Compute Dispatch Key
        # If explicit device arg exists, use it. Else use self.device() or default.
        # For factories, device is usually passed.
        # For methods, use self.device().
        
        dispatch_key_source = "Device(DeviceType::CPU)" # Default fallback
        
        # Find 'device' arg
        device_arg = next((arg for arg in f['args'] if arg['name'] == 'device'), None)
        
        if device_arg:
            dispatch_key_source = "device"
        elif f['variants'] == 'method':
            dispatch_key_source = "device()" # this->device()
        
        lines.append(f"    DispatchKey key = computeDispatchKey({dispatch_key_source});")
        
        # 3. Call DispatchStub
        # DispatchStub<Return, Args...>::call(op_name, key, args...)
        
        template_args = [f['return_type']]
        call_args = [f'"{f["name"]}"', "key"]
        
        for arg in f['args']:
            template_args.append(arg['stub_type'])
            # Pass *this for self if it's a method and argument is 'self'
            if f['variants'] == 'method' and arg['name'] == 'self':
                call_args.append("*this")
            else:
                call_args.append(arg['name'])
                
        template_str = ", ".join(template_args)
        call_str = ", ".join(call_args)
        
        lines.append(f"    return DispatchStub<{template_str}>::call({call_str});")
        lines.append("}")
        lines.append("")
        
    lines.append("} // namespace tensorplay")
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yaml', required=True, help='Path to native_functions.yaml')
    parser.add_argument('--out_dir', required=True, help='Output directory')
    args = parser.parse_args()
    
    with open(args.yaml, 'r') as f:
        data = yaml.safe_load(f)
        
    if data is None:
        data = []
        
    funcs = []
    for item in data:
        f = parse_func(item['func'])
        f['variants'] = item.get('variants', 'function')
        funcs.append(f)
        
    if not os.path.exists(args.out_dir):
        os.makedirs(args.out_dir)
        
    header_path = os.path.join(args.out_dir, "TensorGenerated.h")
    cpp_path = os.path.join(args.out_dir, "TensorGenerated.cpp")
    
    with open(header_path, 'w') as f:
        f.write(generate_header(funcs))
        
    with open(cpp_path, 'w') as f:
        f.write(generate_cpp(funcs))
        
    print(f"Generated {header_path} and {cpp_path}")

if __name__ == "__main__":
    main()
